//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int VehicleID { get; set; }
        public int DealerID { get; set; }
        public int Make { get; set; }
        public string Model { get; set; }
        public string Colour { get; set; }
        public string Registration { get; set; }
        public string License_Plate { get; set; }
        public string Council { get; set; }
        public int Seats { get; set; }
        public string Wheel_Drive { get; set; }
        public string FuelType { get; set; }
        public int Mileage { get; set; }
        public double Price { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public bool IsApproverd { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
